In [20]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [21]:
dataset=pd.read_csv('car_evaluation.csv')
dataset.columns =['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'class']
dataset['doors']=dataset['doors'].replace(['5more'],5)
dataset['persons']=dataset['persons'].replace(['more'],5)
df=dataset.dropna(how='any')
df


buying  maint doors persons lug_boot safety  class
0     vhigh  vhigh     2       2    small    med  unacc
1     vhigh  vhigh     2       2    small   high  unacc
2     vhigh  vhigh     2       2      med    low  unacc
3     vhigh  vhigh     2       2      med    med  unacc
4     vhigh  vhigh     2       2      med   high  unacc
...     ...    ...   ...     ...      ...    ...    ...
1722    low    low     5       5      med    med   good
1723    low    low     5       5      med   high  vgood
1724    low    low     5       5      big    low  unacc
1725    low    low     5       5      big    med   good
1726    low    low     5       5      big   high  vgood

[1727 rows x 7 columns]

In [22]:
X=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [26]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X[:,0]=le.fit_transform(X[:,0])
X[:,1]=le.fit_transform(X[:,1])
X[:,4]=le.fit_transform(X[:,4])
X[:,5]=le.fit_transform(X[:,5])
y=le.fit_transform(y)

In [27]:
y=y.reshape(len(y),1)

In [28]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=0)

In [30]:
from sklearn.tree import DecisionTreeClassifier
DTC=DecisionTreeClassifier(criterion='entropy',random_state=0)
DTC.fit(X_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

In [31]:
y_pred = DTC.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [0 1]
 [2 2]
 [2 2]
 [1 1]
 [0 0]
 [2 2]
 [2 2]
 [0 0]
 [2 2]
 [0 0]
 [0 0]
 [2 2]
 [2 2]
 [0 0]
 [2 2]
 [2 2]
 [2 2]
 [1 1]
 [2 0]
 [2 2]
 [2 2]
 [0 0]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [1 1]
 [0 0]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [0 0]
 [2 2]
 [0 0]
 [2 2]
 [2 2]
 [2 2]
 [0 0]
 [0 0]
 [2 2]
 [0 0]
 [0 0]
 [0 0]
 [2 2]
 [2 0]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [0 0]
 [2 2]
 [2 2]
 [2 0]
 [2 2]
 [0 0]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [0 1]
 [3 3]
 [2 2]
 [0 0]
 [2 2]
 [2 2]
 [0 0]
 [0 0]
 [0 0]
 [2 2]
 [0 0]
 [0 0]
 [2 2]
 [3 3]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [3 3]
 [0 0]
 [0 0]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [3 3]
 [0 0]
 [2 2]
 [2 2]
 [0 0]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [3 3]
 [2 2]
 [1 1]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [0 0]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [1 1]
 [2 2]
 [2 2]
 [2 2]
 [3 3]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [0 0]
 [0 0]
 [2 2]
 [2 2]
 [2 2]
 [2 2]

In [32]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_test, y_pred)*100)

[[ 87   3   6   0]
 [  3  15   0   0]
 [  0   0 298   0]
 [  0   0   0  20]]
97.22222222222221
